name: Print Environment Variables

on:
  push:
    branches:
      - main

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: learning
        run: "echo hello how are you"
      - name: list env
        run: printenv